63d6dc093b6ccbf046d59105
63d6ce1a7b3b8b234193bccf

###
POST http://localhost:3001/users/sendchat HTTP/1.1
content-type: application/json

{
    "userID1": "63d6dc093b6ccbf046d59105",
    "userID2": "63d6ce1a7b3b8b234193bccf",
    "message": "sssss"
}

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3951.0017059452853!2d112.61641921425377!3d-7.998759294239529!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e788394af4940d5%3A0x5b2817ac757dbb4b!2sMie%20Gacoan%20Sukun!5e0!3m2!1sid!2sid!4v1679980741180!5m2!1sid!2sid" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

###
POST http://localhost:3001/restaurants HTTP/1.1
content-type: application/json

{
      "name":"Mie Gacoan",
      "desc":"Restoran mie Gacoan adalah sebuah restoran yang terkenal di Indonesia karena spesialisasinya dalam menyajikan berbagai macam hidangan mie dengan rasa yang lezat dan beragam. Restoran ini memiliki konsep warung mie yang sederhana dan ramah lingkungan dengan suasana yang santai dan nyaman.

Mie Gacoan menyajikan berbagai jenis mie seperti mie ayam, mie goreng, mie kuah, mie seafood, dan mie spesial yang diolah dengan bahan-bahan berkualitas tinggi dan dibuat secara fresh setiap hari. Selain itu, restoran ini juga menyediakan berbagai pilihan topping dan saus yang dapat disesuaikan dengan selera pengunjung.

Selain hidangan mie, restoran ini juga menyediakan berbagai menu makanan pendamping seperti pangsit, siomay, batagor, tahu isi, dan masih banyak lagi. Semua hidangan yang disajikan di restoran mie Gacoan diproses dengan cara yang higienis dan dijamin kebersihannya sehingga aman untuk dikonsumsi.

Restoran mie Gacoan telah memiliki banyak cabang di berbagai kota di Indonesia dan menjadi pilihan favorit bagi banyak orang karena selain rasa yang enak, harganya juga terjangkau dan pelayanan yang ramah dan cepat.",
      "map":"apakek",
      "image":"apakek",
      "categories":"asdasd",
      "minPrice":100000,
      "maxPrice":200000,
      "isOpen":true,
      "rating":[true,true,true,false,false]
}

###
GET http://localhost:3001/restaurants HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/restaurants/categories/apakek HTTP/1.1
content-type: application/json


###
PATCH http://localhost:3001/users/getchat HTTP/1.1
content-type: application/json

{
    "userID2": "63d6dc093b6ccbf046d59105",
    "userID1": "63d6ce1a7b3b8b234193bccf"
}

###
POST http://localhost:3001/auth/sendfeedback HTTP/1.1
content-type: application/json

{
    "name" : "Asep Priyadi",
    "subject": "Portfolio Message",
    "feedback" : "lah kok iso"
}

###
POST http://localhost:3001/posts HTTP/1.1
content-type: application/json

{
    "userId" : "63e2682368751243c462249c",
    "description" : "woooooooooooooooooooooooooooooooooooooooo",
    "picturePat" : "gada"
}
###
POST http://localhost:3001/challenge/createchallenge HTTP/1.1
content-type: application/json

{
      "title": "HTML Dasar",
      "desc": "belajar html di wpu",
      "data": [
        {
            "title": "Pendahuluan",
            "desc": "html doang",
            "video": "https://www.youtube.com/embed/NBZ9Ro6UKV8",
            "date": ""
        },
        {
            "title": "Hello World!",
            "desc": "html doang",
            "video": "https://www.youtube.com/embed/1NicaVOCXHA",
            "date": ""
        },
        {
            "title": "Code Editor",
            "desc": "html doang",
            "video": "https://www.youtube.com/embed/3sLSi9L5nWE",
            "date": ""
        },
        {
            "title": "Pendahuluan",
            "desc": "html doang",
            "video": "https://www.youtube.com/embed/NBZ9Ro6UKV8",
            "date": ""
        },
        {
            "title": "Hello World!",
            "desc": "html doang",
            "video": "https://www.youtube.com/embed/1NicaVOCXHA",
            "date": ""
        },
        {
            "title": "Code Editor",
            "desc": "html doang",
            "video": "https://www.youtube.com/embed/3sLSi9L5nWE",
            "date": ""
        },
        {
            "title": "Pendahuluan",
            "desc": "html doang",
            "video": "https://www.youtube.com/embed/NBZ9Ro6UKV8",
            "date": ""
        },
        {
            "title": "Hello World!",
            "desc": "html doang",
            "video": "https://www.youtube.com/embed/1NicaVOCXHA",
            "date": ""
        },
        {
            "title": "Code Editor",
            "desc": "html doang",
            "video": "https://www.youtube.com/embed/3sLSi9L5nWE",
            "date": ""
        },
      ],
      "startDate": "asdasd"
}

###
GET http://localhost:3001/challenge/getchallenge HTTP/1.1

content-type: application/json
id: "63f82f3e2ba05a8b4a5b684f"

###
GET http://localhost:3001/challenge/getallchallenge HTTP/1.1

content-type: application/json
id: 63f4a2a6983f4f0c42bb0dcf


###
patch http://localhost:3001/challenge/joinChallenge HTTP/1.1
content-type: application/json

{
    "userId" : "63e2682368751243c462249c",
    "challengeId" : "63f82f3e2ba05a8b4a5b684f"
}


###
POST https://worldwide-restaurants.p.rapidapi.com/search HTTP/1.1
content-type: application/x-www-form-urlencoded
X-RapidAPI-Key: d664673b35msh5c57c97780cf088p1c399djsn27c112b16e01
X-RapidAPI-Host: worldwide-restaurants.p.rapidapi.com

{
    "location_id" : "297704",
    "limit" : "30",
    "language" : "en_US",
    "currency": "USD"
}
