63d6dc093b6ccbf046d59105
63d6ce1a7b3b8b234193bccf

###
POST http://localhost:3001/users/sendchat HTTP/1.1
content-type: application/json

{
    "userID1": "63d6dc093b6ccbf046d59105",
    "userID2": "63d6ce1a7b3b8b234193bccf",
    "message": "sssss"
}

###
POST http://localhost:3001/restaurants HTTP/1.1
content-type: application/json

{
      "name":"asdasd",
      "desc":"apakek",
      "map":"apakek",
      "image":"apakek",
      "categories":"asdasd",
      "minPrice":100,
      "maxPrice":200,
      "isOpen":true,
      "rating":[true,true,true,false,false]
}

###
GET http://localhost:3001/restaurants HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/restaurants/categories/apakek HTTP/1.1
content-type: application/json


###
PATCH http://localhost:3001/users/getchat HTTP/1.1
content-type: application/json

{
    "userID2": "63d6dc093b6ccbf046d59105",
    "userID1": "63d6ce1a7b3b8b234193bccf"
}

###
POST http://localhost:3001/auth/sendfeedback HTTP/1.1
content-type: application/json

{
    "name" : "Asep Priyadi",
    "subject": "Portfolio Message",
    "feedback" : "lah kok iso"
}

###
POST http://localhost:3001/posts HTTP/1.1
content-type: application/json

{
    "userId" : "63e2682368751243c462249c",
    "description" : "woooooooooooooooooooooooooooooooooooooooo",
    "picturePat" : "gada"
}
###
POST http://localhost:3001/challenge/createchallenge HTTP/1.1
content-type: application/json

{
      "title": "HTML Dasar",
      "desc": "belajar html di wpu",
      "data": [
        {
            "title": "Pendahuluan",
            "desc": "html doang",
            "video": "https://www.youtube.com/embed/NBZ9Ro6UKV8",
            "date": ""
        },
        {
            "title": "Hello World!",
            "desc": "html doang",
            "video": "https://www.youtube.com/embed/1NicaVOCXHA",
            "date": ""
        },
        {
            "title": "Code Editor",
            "desc": "html doang",
            "video": "https://www.youtube.com/embed/3sLSi9L5nWE",
            "date": ""
        },
        {
            "title": "Pendahuluan",
            "desc": "html doang",
            "video": "https://www.youtube.com/embed/NBZ9Ro6UKV8",
            "date": ""
        },
        {
            "title": "Hello World!",
            "desc": "html doang",
            "video": "https://www.youtube.com/embed/1NicaVOCXHA",
            "date": ""
        },
        {
            "title": "Code Editor",
            "desc": "html doang",
            "video": "https://www.youtube.com/embed/3sLSi9L5nWE",
            "date": ""
        },
        {
            "title": "Pendahuluan",
            "desc": "html doang",
            "video": "https://www.youtube.com/embed/NBZ9Ro6UKV8",
            "date": ""
        },
        {
            "title": "Hello World!",
            "desc": "html doang",
            "video": "https://www.youtube.com/embed/1NicaVOCXHA",
            "date": ""
        },
        {
            "title": "Code Editor",
            "desc": "html doang",
            "video": "https://www.youtube.com/embed/3sLSi9L5nWE",
            "date": ""
        },
      ],
      "startDate": "asdasd"
}

###
GET http://localhost:3001/challenge/getchallenge HTTP/1.1

content-type: application/json
id: "63f82f3e2ba05a8b4a5b684f"

###
GET http://localhost:3001/challenge/getallchallenge HTTP/1.1

content-type: application/json
id: 63f4a2a6983f4f0c42bb0dcf


###
patch http://localhost:3001/challenge/joinChallenge HTTP/1.1
content-type: application/json

{
    "userId" : "63e2682368751243c462249c",
    "challengeId" : "63f82f3e2ba05a8b4a5b684f"
}


###
POST https://worldwide-restaurants.p.rapidapi.com/search HTTP/1.1
content-type: application/x-www-form-urlencoded
X-RapidAPI-Key: d664673b35msh5c57c97780cf088p1c399djsn27c112b16e01
X-RapidAPI-Host: worldwide-restaurants.p.rapidapi.com

{
    "location_id" : "297704",
    "limit" : "30",
    "language" : "en_US",
    "currency": "USD"
}
